sudo: false

language: php

php:
    - 7.4
    - 8.0

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install --no-interaction --prefer-dist

script:
    - ./vendor/bin/phpcs . -p --standard=./phpcs.xml
